<?php

/*
 * This file is part of the ixnode/php-iban project.
 *
 * (c) Björn Hempel <https://www.hempel.li/>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Ixnode\PhpIban\Tests\Unit;

use Ixnode\PhpException\Case\CaseUnsupportedException;
use Ixnode\PhpIban\Exception\AccountParseException;
use Ixnode\PhpIban\Exception\IbanParseException;
use Ixnode\PhpIban\Iban;
use Ixnode\PhpIban\IbanFormat;
use Ixnode\PhpIban\Validator;
use PHPUnit\Framework\TestCase;

/**
 * Class ValidatorTest
 *
 * @author Björn Hempel <bjoern@hempel.li>
 * @version 0.1.0 (2023-09-02)
 * @since 0.1.0 (2023-09-02) First version.
 * @link Validator
 * @SuppressWarnings(PHPMD.ExcessiveClassLength)
 */
final class ValidatorTest extends TestCase
{
    /**
     * Test wrapper.
     *
     * @dataProvider dataProviderIban
     * @dataProvider dataProviderIbanCountries
     *
     * @test
     * @testdox $number) Test account number: "$accountNumber"
     * @param int $number
     * @param Iban $given
     * @param bool $valid
     * @param string|null $lastError
     * @param array<string, mixed> $expected
     * @throws AccountParseException
     * @throws CaseUnsupportedException
     * @throws IbanParseException
     */
    public function wrapperIban(
        int $number,
        Iban $given,
        bool $valid,
        string|null $lastError,
        array $expected,
    ): void
    {
        /* Arrange */

        /* Act */
        $validator = new Validator($given);

        /* Assert */
        $this->assertIsNumeric($number); // To avoid phpmd warning.
        $this->assertSame($validator->isValid(), $valid);
        $this->assertSame($validator->getLastError(), $lastError);

        $this->assertSame([
            IbanFormat::KEY_COUNTRY_CODE,
            IbanFormat::KEY_IBAN_CHECK_DIGITS,
            IbanFormat::KEY_NATIONAL_BANK_CODE,
            IbanFormat::KEY_ACCOUNT_NUMBER,
            IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER,
            IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER,
            IbanFormat::KEY_CURRENCY_CODE,
            IbanFormat::KEY_OWNER_ACCOUNT_NUMBER,
            IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX,
            IbanFormat::KEY_BIC_BANK_CODE,
            IbanFormat::KEY_BRANCH_CODE,
            IbanFormat::KEY_ACCOUNT_TYPE,
            IbanFormat::KEY_NATIONAL_CHECK_DIGITS,
            IbanFormat::KEY_IBAN_FORMATTED,
        ], array_keys($expected));

        $iban = $validator->getIban();
        $account = $validator->getAccount();

        $this->assertSame($expected, [
            IbanFormat::KEY_COUNTRY_CODE => $iban->getCountryCode(),
            IbanFormat::KEY_IBAN_CHECK_DIGITS => $iban->getIbanCheckDigits(),
            IbanFormat::KEY_NATIONAL_BANK_CODE => $account?->getNationalBankCode(),
            IbanFormat::KEY_ACCOUNT_NUMBER => $account?->getAccountNumber(),
            IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => $account?->getBalanceAccountNumber(),
            IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => $account?->getNationalIdentificationNumber(),
            IbanFormat::KEY_CURRENCY_CODE => $account?->getCurrencyCode(),
            IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => $account?->getOwnerAccountNumber(),
            IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => $account?->getAccountNumberPrefix(),
            IbanFormat::KEY_BIC_BANK_CODE => $account?->getBicBankCode(),
            IbanFormat::KEY_BRANCH_CODE => $account?->getBranchCode(),
            IbanFormat::KEY_ACCOUNT_TYPE => $account?->getAccountType(),
            IbanFormat::KEY_NATIONAL_CHECK_DIGITS => $account?->getNationalCheckDigits(),
            IbanFormat::KEY_IBAN_FORMATTED => $iban->getIbanFormatted(),
        ]);
    }

    /**
     * Data provider.
     *
     * https://wise.com/de/iban/checker
     *
     * @return array<int, array<int, mixed>>
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    public function dataProviderIban(): array
    {
        $number = 0;

        return [

            /**
             * AT, CH, DE, LI: Simple IBAN validator test (positive true tests).
             *
             * @see [AT,CH,DE,LI] https://ibanvalidieren.de/beispiele.html
             */
            [++$number, new Iban('AT026000000001349870'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'AT',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '02',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '60000',
                IbanFormat::KEY_ACCOUNT_NUMBER => '00001349870',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'AT02 6000 0000 0134 9870',
            ]],
            [++$number, new Iban('CH0209000000100013997'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'CH',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '02',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '09000',
                IbanFormat::KEY_ACCOUNT_NUMBER => '000100013997',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'CH02 0900 0000 1000 1399 7',
            ]],
            [++$number, new Iban('DE02120300000000202051'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'DE',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '02',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '12030000',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0000202051',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'DE02 1203 0000 0000 2020 51',
            ]],
            [++$number, new Iban('LI0208800000017197386'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'LI',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '02',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '08800',
                IbanFormat::KEY_ACCOUNT_NUMBER => '000017197386',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'LI02 0880 0000 0171 9738 6',
            ]],

            /**
             * ES: Simple IBAN validator test (positive true tests).
             *
             * @see https://www.iban.de/iban-laenderliste.html
             * @see https://de.iban.com/struktur
             */
            [++$number, new Iban('ES9121000418450200051332'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'ES',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '91',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '2100',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0200051332',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '0418',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '45',
                IbanFormat::KEY_IBAN_FORMATTED => 'ES91 2100 0418 4502 0005 1332',
            ]],
            [++$number, new Iban('ES6720310000010118272402'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'ES',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '67',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '2031',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0118272402',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '0000',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '01',
                IbanFormat::KEY_IBAN_FORMATTED => 'ES67 2031 0000 0101 1827 2402',
            ]],

            /**
             * FR: Simple IBAN validator test (positive true tests).
             *
             * @see https://www.iban.de/iban-laenderliste.html
             * @see https://de.iban.com/struktur
             */
            [++$number, new Iban('FR1420041010050500013M02606'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'FR',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '14',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '20041',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0500013M026',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '01005',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '06',
                IbanFormat::KEY_IBAN_FORMATTED => 'FR14 2004 1010 0505 0001 3M02 606',
            ]],
            [++$number, new Iban('FR7630027175330002005370159'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'FR',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '76',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '30027',
                IbanFormat::KEY_ACCOUNT_NUMBER => '00020053701',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '17533',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '59',
                IbanFormat::KEY_IBAN_FORMATTED => 'FR76 3002 7175 3300 0200 5370 159',
            ]],
            [++$number, new Iban('FR7630006000011234567890189'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'FR',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '76',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '30006',
                IbanFormat::KEY_ACCOUNT_NUMBER => '12345678901',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '00001',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '89',
                IbanFormat::KEY_IBAN_FORMATTED => 'FR76 3000 6000 0112 3456 7890 189',
            ]],

            /**
             * Wrong checksum (positive false tests).
             */
            [++$number, new Iban('DE03120300000000202051'), false, 'The checksum does not match.', [
                IbanFormat::KEY_COUNTRY_CODE => 'DE',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '03',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '12030000',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0000202051',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'DE03 1203 0000 0000 2020 51',
            ]],
            [++$number, new Iban('FR7530006000011234567890189'), false, 'The checksum does not match.', [
                IbanFormat::KEY_COUNTRY_CODE => 'FR',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '75',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '30006',
                IbanFormat::KEY_ACCOUNT_NUMBER => '12345678901',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '00001',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '89',
                IbanFormat::KEY_IBAN_FORMATTED => 'FR75 3000 6000 0112 3456 7890 189',
            ]],

            /**
             * Wrong length (positive false tests).
             */
            [++$number, new Iban('DE0212030000000020205'), false, 'Invalid length of IBAN given: "DE0212030000000020205" (expected: "DEkkbbbbbbbbcccccccccc").', [
                IbanFormat::KEY_COUNTRY_CODE => null,
                IbanFormat::KEY_IBAN_CHECK_DIGITS => null,
                IbanFormat::KEY_NATIONAL_BANK_CODE => null,
                IbanFormat::KEY_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'DE02 1203 0000 0000 2020 5',
            ]],
            [++$number, new Iban('DE021203000000002020512'), false, 'Invalid length of IBAN given: "DE021203000000002020512" (expected: "DEkkbbbbbbbbcccccccccc").', [
                IbanFormat::KEY_COUNTRY_CODE => null,
                IbanFormat::KEY_IBAN_CHECK_DIGITS => null,
                IbanFormat::KEY_NATIONAL_BANK_CODE => null,
                IbanFormat::KEY_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'DE02 1203 0000 0000 2020 512',
            ]],

            /**
             * Wrong country (positive false tests).
             */
            [++$number, new Iban('XX02120300000000202051'), false, 'The given country "XX" is not supported yet.', [
                IbanFormat::KEY_COUNTRY_CODE => null,
                IbanFormat::KEY_IBAN_CHECK_DIGITS => null,
                IbanFormat::KEY_NATIONAL_BANK_CODE => null,
                IbanFormat::KEY_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'XX02 1203 0000 0000 2020 51',
            ]],
        ];
    }

    /**
     * Data provider.
     *
     * https://wise.com/de/iban/checker
     *
     * @return array<int, array<int, mixed>>
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    public function dataProviderIbanCountries(): array
    {
        $number = 0;

        return [
            [++$number, new Iban('AD1400080001001234567890'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'AD',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '14',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '0008',
                IbanFormat::KEY_ACCOUNT_NUMBER => '001234567890',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '0001',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'AD14 0008 0001 0012 3456 7890',
            ]],
            [++$number, new Iban('AE460090000000123456789'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'AE',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '46',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '009',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0000000123456789',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'AE46 0090 0000 0012 3456 789',
            ]],
            [++$number, new Iban('AL35202111090000000001234567'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'AL',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '35',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '202',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0000000001234567',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '1110',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '9',
                IbanFormat::KEY_IBAN_FORMATTED => 'AL35 2021 1109 0000 0000 0123 4567',
            ]],
            [++$number, new Iban('AT026000000001349870'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'AT',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '02',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '60000',
                IbanFormat::KEY_ACCOUNT_NUMBER => '00001349870',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'AT02 6000 0000 0134 9870',
            ]],
            [++$number, new Iban('AZ96AZEJ00000000001234567890'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'AZ',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '96',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'AZEJ',
                IbanFormat::KEY_ACCOUNT_NUMBER => '00000000001234567890',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'AZ96 AZEJ 0000 0000 0012 3456 7890',
            ]],
            [++$number, new Iban('BA393385804800211234'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'BA',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '39',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '338',
                IbanFormat::KEY_ACCOUNT_NUMBER => '48002112',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '580',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '34',
                IbanFormat::KEY_IBAN_FORMATTED => 'BA39 3385 8048 0021 1234',
            ]],
            [++$number, new Iban('BE71096123456769'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'BE',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '71',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '096',
                IbanFormat::KEY_ACCOUNT_NUMBER => '1234567',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '69',
                IbanFormat::KEY_IBAN_FORMATTED => 'BE71 0961 2345 6769',
            ]],
            [++$number, new Iban('BH02CITI00001077181611'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'BH',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '02',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'CITI',
                IbanFormat::KEY_ACCOUNT_NUMBER => '00001077181611',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'BH02 CITI 0000 1077 1816 11',
            ]],
            [++$number, new Iban('BG18RZBB91550123456789'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'BG',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '18',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'RZBB',
                IbanFormat::KEY_ACCOUNT_NUMBER => '23456789',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '9155',
                IbanFormat::KEY_ACCOUNT_TYPE => '01',
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'BG18 RZBB 9155 0123 4567 89',
            ]],
            [++$number, new Iban('BR1500000000000010932840814P2'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'BR',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '15',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '00000000',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0932840814',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => '2',
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '00001',
                IbanFormat::KEY_ACCOUNT_TYPE => 'P',
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'BR15 0000 0000 0000 1093 2840 814P 2',
            ]],
            [++$number, new Iban('BY86AKBB10100000002966000000'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'BY',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '86',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'AKBB',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0000002966000000',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => '1010',
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'BY86 AKBB 1010 0000 0029 6600 0000',
            ]],
            [++$number, new Iban('CH0209000000100013997'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'CH',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '02',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '09000',
                IbanFormat::KEY_ACCOUNT_NUMBER => '000100013997',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'CH02 0900 0000 1000 1399 7',
            ]],
            [++$number, new Iban('CR23015108410026012345'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'CR',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '23',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '151',
                IbanFormat::KEY_ACCOUNT_NUMBER => '08410026012345',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'CR23 0151 0841 0026 0123 45',
            ]],
            [++$number, new Iban('CY21002001950000357001234567'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'CY',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '21',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '002',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0000357001234567',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '00195',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'CY21 0020 0195 0000 3570 0123 4567',
            ]],
            [++$number, new Iban('CZ5508000000001234567899'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'CZ',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '55',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '0800',
                IbanFormat::KEY_ACCOUNT_NUMBER => '1234567899',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => '000000',
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'CZ55 0800 0000 0012 3456 7899',
            ]],
            [++$number, new Iban('DE02120300000000202051'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'DE',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '02',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '12030000',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0000202051',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'DE02 1203 0000 0000 2020 51',
            ]],
            [++$number, new Iban('DK9520000123456789'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'DK',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '95',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '2000',
                IbanFormat::KEY_ACCOUNT_NUMBER => '012345678',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '9',
                IbanFormat::KEY_IBAN_FORMATTED => 'DK95 2000 0123 4567 89',
            ]],
            [++$number, new Iban('DO28BAGR00000001212453611324'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'DO',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '28',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'BAGR',
                IbanFormat::KEY_ACCOUNT_NUMBER => '00000001212453611324',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'DO28 BAGR 0000 0001 2124 5361 1324',
            ]],
            [++$number, new Iban('EE471000001020145685'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'EE',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '47',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '10',
                IbanFormat::KEY_ACCOUNT_NUMBER => '00102014568',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '00',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '5',
                IbanFormat::KEY_IBAN_FORMATTED => 'EE47 1000 0010 2014 5685',
            ]],
            [++$number, new Iban('EG800002000156789012345180002'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'EG',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '80',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '0002',
                IbanFormat::KEY_ACCOUNT_NUMBER => '56789012345180002',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '0001',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'EG80 0002 0001 5678 9012 3451 8000 2',
            ]],
            [++$number, new Iban('ES9121000418450200051332'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'ES',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '91',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '2100',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0200051332',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '0418',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '45',
                IbanFormat::KEY_IBAN_FORMATTED => 'ES91 2100 0418 4502 0005 1332',
            ]],
            [++$number, new Iban('FI1410093000123458'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'FI',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '14',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '100930',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0012345',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '8',
                IbanFormat::KEY_IBAN_FORMATTED => 'FI14 1009 3000 1234 58',
            ]],
            [++$number, new Iban('FO9264600123456789'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'FO',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '92',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '6460',
                IbanFormat::KEY_ACCOUNT_NUMBER => '012345678',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '9',
                IbanFormat::KEY_IBAN_FORMATTED => 'FO92 6460 0123 4567 89',
            ]],
            [++$number, new Iban('FR1420041010050500013M02606'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'FR',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '14',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '20041',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0500013M026',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '01005',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '06',
                IbanFormat::KEY_IBAN_FORMATTED => 'FR14 2004 1010 0505 0001 3M02 606',
            ]],
            [++$number, new Iban('GE60NB0000000123456789'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'GE',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '60',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'NB',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0000000123456789',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'GE60 NB00 0000 0123 4567 89',
            ]],
            [++$number, new Iban('GB29NWBK60161331926819'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'GB',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '29',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'NWBK',
                IbanFormat::KEY_ACCOUNT_NUMBER => '31926819',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '601613',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'GB29 NWBK 6016 1331 9268 19',
            ]],
            [++$number, new Iban('GI75NWBK000000007099453'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'GI',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '75',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'NWBK',
                IbanFormat::KEY_ACCOUNT_NUMBER => '000000007099453',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'GI75 NWBK 0000 0000 7099 453',
            ]],
            [++$number, new Iban('GL8964710123456789'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'GL',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '89',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '6471',
                IbanFormat::KEY_ACCOUNT_NUMBER => '012345678',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '9',
                IbanFormat::KEY_IBAN_FORMATTED => 'GL89 6471 0123 4567 89',
            ]],
            [++$number, new Iban('GR9608100010000001234567890'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'GR',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '96',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '081',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0000001234567890',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '0001',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'GR96 0810 0010 0000 0123 4567 890',
            ]],
            [++$number, new Iban('GT20AGRO00000000001234567890'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'GT',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '20',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'AGRO',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0000001234567890',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => '00',
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => '00',
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'GT20 AGRO 0000 0000 0012 3456 7890',
            ]],
            [++$number, new Iban('IE64IRCE92050112345678'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'IE',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '64',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '920501',
                IbanFormat::KEY_ACCOUNT_NUMBER => '12345678',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => 'IRCE',
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'IE64 IRCE 9205 0112 3456 78',
            ]],
            [++$number, new Iban('HR1723600001101234565'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'HR',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '17',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '2360000',
                IbanFormat::KEY_ACCOUNT_NUMBER => '1101234565',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'HR17 2360 0001 1012 3456 5',
            ]],
            [++$number, new Iban('HU02116000060000000012345676'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'HU',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '02',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '116',
                IbanFormat::KEY_ACCOUNT_NUMBER => '000000001234567',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '0000',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '6',
                IbanFormat::KEY_IBAN_FORMATTED => 'HU02 1160 0006 0000 0000 1234 5676',
            ]],
            [++$number, new Iban('IL170108000000012612345'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'IL',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '17',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '010',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0000012612345',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '800',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'IL17 0108 0000 0001 2612 345',
            ]],
            [++$number, new Iban('IQ20CBIQ861800101010500'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'IQ',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '20',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'CBIQ',
                IbanFormat::KEY_ACCOUNT_NUMBER => '800101010500',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '861',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'IQ20 CBIQ 8618 0010 1010 500',
            ]],
            [++$number, new Iban('IS030001121234561234567890'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'IS',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '03',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '00',
                IbanFormat::KEY_ACCOUNT_NUMBER => '123456',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => '1234567890',
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '01',
                IbanFormat::KEY_ACCOUNT_TYPE => '12',
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'IS03 0001 1212 3456 1234 5678 90',
            ]],
            [++$number, new Iban('IT60X0542811101000000123456'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'IT',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '60',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '05428',
                IbanFormat::KEY_ACCOUNT_NUMBER => '000000123456',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '11101',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => 'X',
                IbanFormat::KEY_IBAN_FORMATTED => 'IT60 X054 2811 1010 0000 0123 456',
            ]],
            [++$number, new Iban('JO71CBJO0000000000001234567890'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'JO',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '71',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'CBJO',
                IbanFormat::KEY_ACCOUNT_NUMBER => '000000001234567890',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '0000',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'JO71 CBJO 0000 0000 0000 1234 5678 90',
            ]],
            [++$number, new Iban('KW81CBKU0000000000001234560101'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'KW',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '81',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'CBKU',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0000000000001234560101',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'KW81 CBKU 0000 0000 0000 1234 5601 01',
            ]],
            [++$number, new Iban('KZ86125KZT5004100100'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'KZ',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '86',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '125',
                IbanFormat::KEY_ACCOUNT_NUMBER => 'KZT5004100100',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'KZ86 125K ZT50 0410 0100',
            ]],
            [++$number, new Iban('LC14BOSL123456789012345678901234'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'LC',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '14',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'BOSL',
                IbanFormat::KEY_ACCOUNT_NUMBER => '123456789012345678901234',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'LC14 BOSL 1234 5678 9012 3456 7890 1234',
            ]],
            [++$number, new Iban('LI0208800000017197386'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'LI',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '02',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '08800',
                IbanFormat::KEY_ACCOUNT_NUMBER => '000017197386',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'LI02 0880 0000 0171 9738 6',
            ]],
            [++$number, new Iban('LB62099900000001001901229114'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'LB',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '62',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '0999',
                IbanFormat::KEY_ACCOUNT_NUMBER => '00000001001901229114',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'LB62 0999 0000 0001 0019 0122 9114',
            ]],
            [++$number, new Iban('LT601010012345678901'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'LT',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '60',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '10100',
                IbanFormat::KEY_ACCOUNT_NUMBER => '12345678901',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'LT60 1010 0123 4567 8901',
            ]],
            [++$number, new Iban('LU120010001234567891'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'LU',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '12',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '001',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0001234567891',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'LU12 0010 0012 3456 7891',
            ]],
            [++$number, new Iban('LV97HABA0012345678910'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'LV',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '97',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'HABA',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0012345678910',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'LV97 HABA 0012 3456 7891 0',
            ]],
            [++$number, new Iban('MK07200002785123453'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'MK',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '07',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '200',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0027851234',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '53',
                IbanFormat::KEY_IBAN_FORMATTED => 'MK07 2000 0278 5123 453',
            ]],
            [++$number, new Iban('MD21EX000000000001234567'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'MD',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '21',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'EX',
                IbanFormat::KEY_ACCOUNT_NUMBER => '000000000001234567',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'MD21 EX00 0000 0000 0123 4567',
            ]],
            [++$number, new Iban('MC5810096180790123456789085'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'MC',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '58',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '10096',
                IbanFormat::KEY_ACCOUNT_NUMBER => '01234567890',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '18079',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '85',
                IbanFormat::KEY_IBAN_FORMATTED => 'MC58 1009 6180 7901 2345 6789 085',
            ]],
            [++$number, new Iban('ME25505000012345678951'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'ME',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '25',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '505',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0000123456789',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '51',
                IbanFormat::KEY_IBAN_FORMATTED => 'ME25 5050 0001 2345 6789 51',
            ]],
            [++$number, new Iban('MR1300020001010000123456753'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'MR',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '13',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '00020',
                IbanFormat::KEY_ACCOUNT_NUMBER => '00001234567',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '00101',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '53',
                IbanFormat::KEY_IBAN_FORMATTED => 'MR13 0002 0001 0100 0012 3456 753',
            ]],
            [++$number, new Iban('MT31MALT01100000000000000000123'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'MT',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '31',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'MALT',
                IbanFormat::KEY_ACCOUNT_NUMBER => '000000000000000123',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '01100',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'MT31 MALT 0110 0000 0000 0000 0000 123',
            ]],
            [++$number, new Iban('MU17BOMM0101101030300200000MUR'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'MU',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '17',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'BOMM01',
                IbanFormat::KEY_ACCOUNT_NUMBER => '101030300200',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => 'MUR',
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '01',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'MU17 BOMM 0101 1010 3030 0200 000M UR',
            ]],
            [++$number, new Iban('NL02ABNA0123456789'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'NL',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '02',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'ABNA',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0123456789',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'NL02 ABNA 0123 4567 89',
            ]],
            [++$number, new Iban('NO8330001234567'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'NO',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '83',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '3000',
                IbanFormat::KEY_ACCOUNT_NUMBER => '123456',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '7',
                IbanFormat::KEY_IBAN_FORMATTED => 'NO83 3000 1234 567',
            ]],
            [++$number, new Iban('PK36SCBL0000001123456702'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'PK',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '36',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'SCBL',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0000001123456702',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'PK36 SCBL 0000 0011 2345 6702',
            ]],
            [++$number, new Iban('PL10105000997603123456789123'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'PL',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '10',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '105',
                IbanFormat::KEY_ACCOUNT_NUMBER => '7603123456789123',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '0009',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '9',
                IbanFormat::KEY_IBAN_FORMATTED => 'PL10 1050 0099 7603 1234 5678 9123',
            ]],
            [++$number, new Iban('PS92PALS000000000400123456702'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'PS',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '92',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'PALS',
                IbanFormat::KEY_ACCOUNT_NUMBER => '000000000400123456702',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'PS92 PALS 0000 0000 0400 1234 5670 2',
            ]],
            [++$number, new Iban('PT50003600409911001102673'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'PT',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '50',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '0036',
                IbanFormat::KEY_ACCOUNT_NUMBER => '99110011026',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '0040',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '73',
                IbanFormat::KEY_IBAN_FORMATTED => 'PT50 0036 0040 9911 0011 0267 3',
            ]],
            [++$number, new Iban('QA54QNBA000000000000693123456'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'QA',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '54',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'QNBA',
                IbanFormat::KEY_ACCOUNT_NUMBER => '000000000000693123456',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'QA54 QNBA 0000 0000 0000 6931 2345 6',
            ]],
            [++$number, new Iban('RO09BCYP0000001234567890'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'RO',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '09',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'BCYP',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0000001234567890',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'RO09 BCYP 0000 0012 3456 7890',
            ]],
            [++$number, new Iban('RS35105008123123123173'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'RS',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '35',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '105',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0081231231231',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '73',
                IbanFormat::KEY_IBAN_FORMATTED => 'RS35 1050 0812 3123 1231 73',
            ]],
            [++$number, new Iban('SA4420000001234567891234'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'SA',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '44',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '20',
                IbanFormat::KEY_ACCOUNT_NUMBER => '000001234567891234',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'SA44 2000 0001 2345 6789 1234',
            ]],
            [++$number, new Iban('SE7280000810340009783242'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'SE',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '72',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '800',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0081034000978324',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '2',
                IbanFormat::KEY_IBAN_FORMATTED => 'SE72 8000 0810 3400 0978 3242',
            ]],
            [++$number, new Iban('SC52BAHL01031234567890123456USD'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'SC',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '52',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'BAHL01',
                IbanFormat::KEY_ACCOUNT_NUMBER => '1234567890123456',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => 'USD',
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '03',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'SC52 BAHL 0103 1234 5678 9012 3456 USD',
            ]],
            [++$number, new Iban('SI56192001234567892'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'SI',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '56',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '19',
                IbanFormat::KEY_ACCOUNT_NUMBER => '12345678',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '200',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '92',
                IbanFormat::KEY_IBAN_FORMATTED => 'SI56 1920 0123 4567 892',
            ]],
            [++$number, new Iban('SK8975000000000012345671'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'SK',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '89',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '7500',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0012345671',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => '000000',
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'SK89 7500 0000 0000 1234 5671',
            ]],
            [++$number, new Iban('SM86U0322509800000000270100'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'SM',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '86',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '03225',
                IbanFormat::KEY_ACCOUNT_NUMBER => '000000270100',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '09800',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => 'U',
                IbanFormat::KEY_IBAN_FORMATTED => 'SM86 U032 2509 8000 0000 0270 100',
            ]],
            [++$number, new Iban('ST68000100010051845310112'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'ST',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '68',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '0001',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0051845310112',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '0001',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'ST68 0001 0001 0051 8453 1011 2',
            ]],
            [++$number, new Iban('SV43ACAT00000000000000123123'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'SV',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '43',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'ACAT',
                IbanFormat::KEY_ACCOUNT_NUMBER => '00000000000000123123',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'SV43 ACAT 0000 0000 0000 0012 3123',
            ]],
            [++$number, new Iban('TL380010012345678910106'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'TL',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '38',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '001',
                IbanFormat::KEY_ACCOUNT_NUMBER => '00123456789101',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '06',
                IbanFormat::KEY_IBAN_FORMATTED => 'TL38 0010 0123 4567 8910 106',
            ]],
            [++$number, new Iban('TN5910006035183598478831'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'TN',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '59',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '10',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0351835984788',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => '006',
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => '31',
                IbanFormat::KEY_IBAN_FORMATTED => 'TN59 1000 6035 1835 9847 8831',
            ]],
            [++$number, new Iban('TR320010009999901234567890'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'TR',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '32',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '00100',
                IbanFormat::KEY_ACCOUNT_NUMBER => '9999901234567890',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'TR32 0010 0099 9990 1234 5678 90',
            ]],
            [++$number, new Iban('UA903052992990004149123456789'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'UA',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '90',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '305299',
                IbanFormat::KEY_ACCOUNT_NUMBER => '2990004149123456789',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'UA90 3052 9929 9000 4149 1234 5678 9',
            ]],
            [++$number, new Iban('VG96VPVG0000012345678901'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'VG',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '96',
                IbanFormat::KEY_NATIONAL_BANK_CODE => 'VPVG',
                IbanFormat::KEY_ACCOUNT_NUMBER => '0000012345678901',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'VG96 VPVG 0000 0123 4567 8901',
            ]],
            [++$number, new Iban('XK051212012345678906'), true, null, [
                IbanFormat::KEY_COUNTRY_CODE => 'XK',
                IbanFormat::KEY_IBAN_CHECK_DIGITS => '05',
                IbanFormat::KEY_NATIONAL_BANK_CODE => '1212',
                IbanFormat::KEY_ACCOUNT_NUMBER => '012345678906',
                IbanFormat::KEY_BALANCE_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_NATIONAL_IDENTIFICATION_NUMBER => null,
                IbanFormat::KEY_CURRENCY_CODE => null,
                IbanFormat::KEY_OWNER_ACCOUNT_NUMBER => null,
                IbanFormat::KEY_ACCOUNT_NUMBER_PREFIX => null,
                IbanFormat::KEY_BIC_BANK_CODE => null,
                IbanFormat::KEY_BRANCH_CODE => null,
                IbanFormat::KEY_ACCOUNT_TYPE => null,
                IbanFormat::KEY_NATIONAL_CHECK_DIGITS => null,
                IbanFormat::KEY_IBAN_FORMATTED => 'XK05 1212 0123 4567 8906',
            ]],
        ];
    }
}
